### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by 100lic** [ZER-0-NE/EAST-Detector-for-text-detection-using-OpenCV#1]
endx = int(offsetx + (cos * xdata1[x]) + (sin * xdata2[x]))
TypeError: only size-1 arrays can be converted to Python scalars

Hey! I got this error when i run program.

**Comment by junshipeng** [comment]
> endx = int(offsetx + (cos * xdata1[x]) + (sin * xdata2[x]))
> 
> TypeError: only size-1 arrays can be converted to Python scalars
> Hey! I got this error when i run program.

me too

**Comment by ajaykrishnan23** [comment]
same

> ```
> endx = int(offsetx + (cos * xdata1[x]) + (sin * xdata2[x]))
> ```
> 
> TypeError: only size-1 arrays can be converted to Python scalars
> 
> Hey! I got this error when i run program.

same

**Comment by ZER-0-NE** [comment]
@100lic @junshipeng @ajaykrishnan23 can you check once if the error still persists?

**Comment by ZER-0-NE** [comment]
Has been taken care of. Please clone from master, if required.
