### ISSUE TITLE
extract text

### ISSUE THREAD

**Issue by hanane2019** [ZER-0-NE/EAST-Detector-for-text-detection-using-OpenCV#4]
can this program extract text from those images ?

**Comment by ZER-0-NE** [comment]
Not yet.

**Comment by hanane2019** [comment]
can you help me please to extract text from an image ? I will share with you my code , it can extract some informations from a receipt but if a give it another one , it didn't give me correct result ?
Can we keep in touch? this is my address mail: me.saadihanane@gmail.com
